version: '3.7'

services:
    capstone:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./capstone:/capstone
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        environment:
            - DEBUG=1
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'capstone.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()
